### ISSUE TITLE
Remote Settings update

### ISSUE THREAD

**Issue by matcadg** [afawcett/declarative-lookup-rollup-summaries#372]
When organisation starts using custom domain, remote setting has to be updated. Currently package does not allow to update remote setting, as recognizes that setting was already created, despite the fact, that URL is no longer valid. Entry has to be deleted from 'Remote Settings' setup node manually and then re-created using Welcome page.
# minor #nicehave

**Comment by afawcett** [comment]
Thanks, yeah that is a bit of a pain, marked as an enhancement. Cheers! 👍

**Comment by camisotro** [comment]
I thought I'd bump this up again. We had a consulting client come to us in confusion when the DLRS configuration page stopped working after they (without asking us) enabled My Domain. We had to advise them to delete the setting and recreate. If it could update the existing setting that'd be wonderful.

**Comment by afawcett** [comment]
Yeah once this enhancement is done, this will not be an issue. Architecture wise this is a better fix. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/607.

**Comment by camisotro** [comment]
Interesting. Would trigger deployment still depend on the API though?

**Comment by afawcett** [comment]
Yes, the tool would still need to use SOAP Metadata API wrapper, it will be a while if unlikely that they will allow the native MD API to publish code tbh. But at least making the above enhancement reduces the day to day / week to week need once the triggers are deployed.

**Comment by camisotro** [comment]
Makes sense. I guess the remaining use case would still be, admin sets up DLRS, then later on either 1) has an instance migration, 2) creates a sandbox, or 3) enables My Domain. Next time they try to deploy a trigger on a new object they'd still be prompted to create the Remote Site Setting. If DLRS could be smart enough at this point to update the RSS rather than attempt unsuccessfully to create a new one, that'd still have value.

**Comment by afawcett** [comment]
Yeah ok, that adds value, re-opened! :+1:

**Comment by camisotro** [comment]
Interesting, note the following Critical Update launching Spring 18 although it does not appear to be visible in my Spring 18 pre-release yet:
https://releasenotes.docs.salesforce.com/en-us/spring18/release-notes/rn_vf_instance_names_removed.htm#rn_vf_instance_names_removed

** mydomain--c.visualforce.com replaces mydomain--c.na1.visual.force.com **

Auto-activated by March 2019. And the Site Setting that DLRS creates is on the Visualforce domain. So in the next 14 months **every Salesforce instance** will see this domain change, and thus all DLRS users with My Domain will have to at least once adjust their Site Setting to a new one.

**Comment by afawcett** [comment]
Thanks @camisotro will up the priority on this one.

**Comment by camisotro** [comment]
Would the simplest solution be to change <createMetadata> to <upsertMetadata> in the client-side callout?

**Comment by afawcett** [comment]
Fixed in v2.11

**Comment by anspaujd** [comment]
I am getting this error again after the most recent release and the workaround listed above is no longer working. Currently process:

- Click "Remote Site Setting" button on Welcome tab
- Remote Setting is created with "https://thedesaifoundation--dlrs.visualforce.com" domain
- I changed this Remote Setting name and then repeated but the same error still shows up: "Salesforce Metadata API connection failure, click the link below to configure."

Advice?

**Comment by danielconde13** [comment]
Same here: pushing the "Create/Update Remote Site Setting doesn't solve the "Salesforce Metadata API connection failure" issue.

**Comment by stevebackman** [comment]
I for the first time now get this error. Have uninstalelled/re; put in remote site entry manaully; tried in sandbox. Nothing. Are others still getting this? Any new ideas?

**Comment by jimhubert** [comment]
I am getting the same error that @stevebackman and @danielconde13 described above, pushing the "Create/Update Remote Site Setting doesn't solve the "Salesforce Metadata API connection failure" issue.  Any new ideas to try or solutions?

**Comment by JimBTek** [comment]
There have been a lot of Warnings from Salesforce around Custom Metadata access for Spring '20 which a lot of people were upgraded to over the weekend.  Now for users to access Custom Metadata (Which is vital to DLRS), you need to give users access to the specific Custom Metadata via their Profile or a Permission Set.  I would try that and report back.

**Comment by jimhubert** [comment]
Thanks @JimBTek I looked into the Custom Metadata access changes for Spring '20 as you recommended and that looks like it was the problem, things are working correctly after making the changes recommended in the Salesforce documentation at  https://releasenotes.docs.salesforce.com/en-us/winter20/release-notes/rn_forcecom_development_custom_metadata_require_cruc.htm

**Comment by gitsanch** [comment]
@JimBTek  @jimhubert  I tried adding the dlrs Custom Metadata in the System Administrator profile, create/update the remote site settings and still I'm still receiving this issue.

<img width="1657" alt="Screen Shot 2020-04-24 at 10 26 57 AM" src="https://user-images.githubusercontent.com/64231964/80155681-56176e00-8616-11ea-8d76-88b598681d04.png">

**Comment by dgaliano262** [comment]
Hello @JimBTek I am facing hte same issue and curious if another solution was found? I uninstalled/reinstalled. Then I deleted the remote site and recreated manually.  I also assigned the Custom Meta Data access to my profile via permission sets and profile.  Any suggestions would be greatly appreciated!

**Comment by afawcett** [comment]
Hey all - please note - that if you can enable My Domain on the org - this whole connection issue goes away - since the tool then leverages a platform feature that allows SF API access without a remote site.

**Comment by slhyatt77** [comment]
@afawcett  I have an org getting this issue with My Domain enabled. They see this error when they go to the Manage Lookup Rollup Summaries tab. I've removed the existing remote site setting and re-created it. I turned off both lock sessions options in session settings.  I still see this message in the debug of the Welcome screen
"Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor="
