### ISSUE TITLE
dlrs__UniqueName__c duplicates value

### ISSUE THREAD

**Issue by andykallio** [afawcett/declarative-lookup-rollup-summaries#838]
Hello,
So far, one of my users is encountering this error.

`dlrs_CampaignTrigger: execution of AfterUpdate caused by: System.DmlException: Insert failed. First exception on row 0; first error: DUPLICATE_VALUE, duplicate value found: dlrs__UniqueName__c duplicates value on record with id: a2Y0o0000056DSM: [] Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1012, column 1 Class.dlrs.RollupService.handleRollups: line 892, column 1 Class.dlrs.RollupService.triggerHandler: line 311, column 1 Trigger.dlrs_CampaignTrigger: line 7, column 1`

 It's probably no coincidence that I just deployed that trigger. I ran a query  to find the value in dlrs_UniqueName__c for that record, and then I looked for other records that had that value, but it's only that record. The other confounding bit for me is that I don't get the error. So, my permissions as an admin seems to get me around it.

**Comment by JimBTek** [comment]
It seems like someone is trying to update a 2nd record to have the same name as the first, and it is failing. Just a guess.

**Comment by rcsanchez-sim** [comment]
We are receiving this issue as well. There is a specific user that is receiving this issue.

**Comment by afawcett** [comment]
@andykallio are you still getting this error?

**Comment by HemantShukla** [comment]
Hey @afawcett , 

Its still failing for me. I tried to install latest package **2.11.1** thinking that may fix it, but unfortunately upgrade also didn't help. 

We are creating records in sites. 

Thanks,
Hemant

**Comment by jromphfmio** [comment]
Having this issue for Community users, standard CRM users fine.

**Comment by kaddae** [comment]
I'm working in an org encountering this issue for Community users as well. @afawcett  Any idea of the timeline for fixing this?

**Comment by gbickel-nuage** [comment]
@jromphfmio and @kaddae - I had the same issue with the Community users and I was able to resolve this by changing the 'Calculation Sharing Mode' to 'System' (from the default user).  My hunch is that the Guest user which is creating the records from the community doesn't have the sharing visibility into the records that DLRS is creating, so it doesn't see the existing Unique Name records and tries to insert another causing the duplicate error.  Once I changed that to System, the system could see the records and handled it correctly.    Hope this helps - I spent a bit of time trying to figure this out.

![image](https://user-images.githubusercontent.com/61874251/76085420-3dbc9880-5f6f-11ea-92cb-898c1b0cb4de.png)

**Comment by kaddae** [comment]
I was encountering this issue even when calculating in System mode, but thanks for the tip.

**Comment by afawcett** [comment]
This is a problem creating "shadow rollups" (needed to pre v2.11) when using custom metadata type rollups and in during certain race conditions in produciton. Good news! The implementation changed in v2.12. :-)

**Comment by jromphfmio** [comment]
Confirmed my issue is now resolved after upgrading DLRS and doing some field/logs cleanup. Thanks @afawcett !

**Comment by jkurant** [comment]
I see that this item is closed. That said, I am able to post a comment here, so I'm hoping someone can help. 

I am having this same problem but changing to System mode did not fix it. In my case the users are Sites users and have a particular profile for the site, but I cannot grant access to any DLRS objects. We control this via metadata and I changed the settings there. I am not sure if there is another place I would need to go to change the setting.

But can anyone tell me if it just won't be possible for an unauthenticated Sites user to be able to create a Case when there is a rollup summary on Case? I find that it fails in the trigger that probably updates some DLRS object.
